config/routes.rb
Rails.application.routes.draw do
  
  resources :evento_vaquejadas
  resources :circuitos
  resources :operadors
  resources :funcaos
  devise_for :users
  
  get 'home/index'

  root 'home#index'

  

  resources :vaqueiros do
    collection do
      get 'teste'
    end
  end

  get 'home/inicial'
    

end

app/models/operador.rb
class Operador < ActiveRecord::Base
  belongs_to :funcao
  validates_presence_of :nome

  has_many :evento_vaquejada, :dependent => :restrict_with_error 

end

app/controllers/operadors_controller.rb
class OperadorsController < ApplicationController
  before_action :set_operador, only: [:show, :edit, :update, :destroy]

  # GET /operadors
  # GET /operadors.json
  def index
    @operadors = Operador.all
  end

  # GET /operadors/1
  # GET /operadors/1.json
  def show
  end

  # GET /operadors/new
  def new
    @operador = Operador.new
  end

  # GET /operadors/1/edit
  def edit
  end

  # POST /operadors
  # POST /operadors.json
  def create
    @operador = Operador.new(operador_params)

    respond_to do |format|
      if @operador.save
        format.html { redirect_to @operador, notice: 'Operador foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @operador }
      else
        format.html { render :new }
        format.json { render json: @operador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operadors/1
  # PATCH/PUT /operadors/1.json
  def update
    respond_to do |format|
      if @operador.update(operador_params)
        format.html { redirect_to @operador, notice: 'Operador foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @operador }
      else
        format.html { render :edit }
        format.json { render json: @operador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operadors/1
  # DELETE /operadors/1.json
  def destroy
    respond_to do |format|
      if @operador.destroy
        format.html { redirect_to operadors_url, notice: 'Operador foi excluído com sucesso.' }
      else
        format.html { redirect_to operadors_url, alert: @operador.errors.messages[:base]}
      end
      format.json { head :no_content }   
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operador
      @operador = Operador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operador_params
      params.require(:operador).permit(:nome, :nome_reduzido, :funcao_id)
    end
end

app/helpers/operadors_helper.rb
module OperadorsHelper
end

app/views/operadors/_form.html.erb
<%= form_for(@operador) do |f| %>
  <% if @operador.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
      <h4><%= pluralize(@operador.errors.count, "erro(s)") %> Não foi possível salvar Operador:</h4>
      <ul>
          <% @operador.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="form-group col-md-8">
    <%= f.label :nome, class: 'control-label'%><br>
    <%= f.text_field :nome, class: 'form-control'  %>
  </div>
</div> 
<div class="row">
  <div class="form-group col-md-4">
    <%= f.label :nome_reduzido %><br>
    <%= f.text_field :nome_reduzido, class: 'form-control'  %>
  </div>
  <div class="form-group col-md-4">
    <%= f.label 'Função', class: 'control-label'  %><br>
    <%= f.select :funcao_id, 
        options_from_collection_for_select(Funcao.all, :id, :tipo, @operador.funcao_id), 
        { :include_blank => 'Selecione' }, { :class => 'form-control' } %>
  </div>
</div>
  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/operadors/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Editar Operador</h2>
    </div>
    <!-- /.col-lg-12 -->
</div>

<%= render 'form' %>
</br>
<%= link_to 'Visualizar', @operador, class: 'btn btn-default' %> |
<%= link_to 'Voltar', operadors_path, class: 'btn btn-default' %>

app/views/operadors/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Lista de Operadores</h2>
    </div>
    <!-- /.col-lg-12 -->
</div>
<% if notice or alert %>
<div class="alert alert-<%= alert ? 'warning' : 'success' %> alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
  <p id="notice"><%= notice %></p><p id="alert"><%= alert %></p>
</div>
<%end%>

<div class="col-md-12">
  <div class="panel panel-default">
      <div class="panel-heading">
          Operadores
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
          <div class="table-responsive">
              <table class="table table-striped table-bordered table-hover">
                  <thead>
                    <tr>
                      <th>Nome</th>
                      <th>Nome reduzido</th>
                      <th>Função</th>
                      <th colspan="3">Ações</th>
                    </tr>
                  </thead>
                  
                  <tbody>
                    <% @operadors.each do |operador| %>
                      <tr>
                        <td><%= operador.nome %></td>
                        <td><%= operador.nome_reduzido %></td>
                        <td><%= operador.funcao.tipo %></td>
                        <td align="center"><%= link_to 'Visualizar', operador %></td>
                        <td align="center"><%= link_to 'Editar', edit_operador_path(operador) %></td>
                        <td align="center"><%= link_to 'Excluir', operador, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class: 'btn btn-danger' %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table> 
          </div>
    </div>  
  </div>    
</div>

</br>

<%= link_to 'Novo Operador', new_operador_path, class: 'btn btn-primary' %>

app/views/operadors/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Novo Operador</h2>
    </div>
</div>

<%= render 'form' %>
</br>
<%= link_to 'Voltar', operadors_path, class: 'btn btn-default'%>

app/views/operadors/show.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Visualizar Operador</h2>
    </div>
    <!-- /.col-lg-12 -->
</div>

<% unless notice.nil? %>
<div class="alert alert-success alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
  <p id="notice"><%= notice %></p>
</div>
<%end%>

<p>
  <strong>Nome:</strong>
  <%= @operador.nome %>
</p>

<p>
  <strong>Nome reduzido:</strong>
  <%= @operador.nome_reduzido %>
</p>

<p>
  <strong>Função:</strong>
  <%= @operador.funcao.tipo %>
</p>

<%= link_to 'Editar', edit_operador_path(@operador), class: 'btn btn-default' %> |
<%= link_to 'Voltar', operadors_path, class: 'btn btn-default' %>