config/routes.rb
Rails.application.routes.draw do
  
  resources :evento_vaquejadas
  resources :circuitos
  resources :operadors
  resources :funcaos
  devise_for :users
  
  get 'home/index'

  root 'home#index'

  

  resources :vaqueiros do
    collection do
      get 'teste'
    end
  end

  get 'home/inicial'
    

end

app/models/circuito.rb
class Circuito < ActiveRecord::Base
	validates_presence_of :nome, :cidade, :estado, :ano

	has_many :evento_vaquejada, :dependent => :restrict_with_error 
end

app/controllers/circuitos_controller.rb
class CircuitosController < ApplicationController
  before_action :set_circuito, only: [:show, :edit, :update, :destroy]
  
  # GET /circuitos
  # GET /circuitos.json
  def index
    @circuitos = Circuito.all
  end

  # GET /circuitos/1
  # GET /circuitos/1.json
  def show
  end

  # GET /circuitos/new
  def new
    @circuito = Circuito.new
  end

  # GET /circuitos/1/edit
  def edit
  end

  # POST /circuitos
  # POST /circuitos.json
  def create
    @circuito = Circuito.new(circuito_params)

    respond_to do |format|
      if @circuito.save
        format.html { redirect_to @circuito, notice: 'Circuito foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @circuito }
      else
        format.html { render :new }
        format.json { render json: @circuito.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /circuitos/1
  # PATCH/PUT /circuitos/1.json
  def update
    respond_to do |format|
      if @circuito.update(circuito_params)
        format.html { redirect_to @circuito, notice: 'Circuito foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @circuito }
      else
        format.html { render :edit }
        format.json { render json: @circuito.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /circuitos/1
  # DELETE /circuitos/1.json
  def destroy
    respond_to do |format|
      if @circuito.destroy
        format.html { redirect_to circuitos_url, notice: 'Circuito foi excluído com sucesso.' }
      else    
        format.html { redirect_to circuitos_url, alert: @circuito.errors.messages[:base]}
      end  
        format.json { head :no_content }  
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_circuito
      @circuito = Circuito.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def circuito_params
      params.require(:circuito).permit(:nome, :cidade, :estado, :ano, :contato, :telefone_contato, :telefone_contato_2, :descricao)
    end
end

app/helpers/circuitos_helper.rb
module CircuitosHelper
end

app/views/circuitos/_form.html.erb
<%= form_for(@circuito) do |f| %>
  <% if @circuito.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
      <h4><%= pluralize(@circuito.errors.count, "erro(s)") %> Não foi possível salvar o Circuito:</h4>
      <ul>
          <% @circuito.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-9">
      <%= f.label :nome, class: 'control-label' %><br>
      <%= f.text_field :nome, class: 'form-control' %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :ano, class: 'control-label' %><br>
      <%= f.number_field :ano, class: 'form-control' %>
    </div>
  </div>
  <div class="row">  
    <div class="form-group col-md-6">
      <%= f.label :cidade, class: 'control-label' %><br>
      <%= f.text_field :cidade, class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :estado, class: 'control-label' %><br>
      <%= f.text_field :estado, class: 'form-control' %>
    </div>
  </div>
  <div class="row"> 
     <div class="form-group col-md-6">
      <%= f.label :contato, class: 'control-label' %><br>
      <%= f.text_field :contato, class: 'form-control' %>
    </div> 
    <div class="form-group col-md-3">
      <%= f.label :telefone_contato, class: 'control-label' %><br>
      <%= f.text_field :telefone_contato, class: 'form-control' %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :telefone_contato_2, class: 'control-label' %><br>
      <%= f.text_field :telefone_contato_2, class: 'form-control' %>
    </div>
  </div> 
  <div class="row">   
    <div class="form-group col-md-8">
      <%= f.label :descricao, class: 'control-label' %><br>
      <%= f.text_area :descricao, class: 'form-control' %>
    </div>
  </div>
    
  <div class="actions">
    <%= f.submit class: 'btn btn-success'%>
  </div>
<% end %>

app/views/circuitos/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Editar Circuito</h2>
    </div>
</div>

<%= render 'form' %>
</br>
<%= link_to 'Visualizar', @circuito, class: 'btn btn-default'  %> |
<%= link_to 'Voltar', circuitos_path, class: 'btn btn-default'  %>

app/views/circuitos/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Lista de Circuitos</h2>
    </div>
    <!-- /.col-lg-12 -->
</div>
<% if notice or alert%>
<div class="alert alert-<%= alert ? 'warning' : 'success' %> alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
  <p id="notice"><%= notice %></p><p id="alert"><%= alert %></p>
</div>
<%end%>

<div class="col-md-12">
  <div class="panel panel-default">
      <div class="panel-heading">
          Circuitos
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
          <div class="table-responsive">
              <table class="table table-striped table-bordered table-hover">
                  <thead>
                    <tr>
                      <th>Nome</th>
                      <th>Cidade</th>
                      <th>Estado</th>
                      <th>Ano</th>
                      <th>Contato</th>
                      <th>Telefone contato</th>
                      <th colspan="3">Ações</th>
                    </tr>
                  </thead>
                  
                  <tbody>
                     <% @circuitos.each do |circuito| %>
                      <tr>
                        <td><%= circuito.nome %></td>
                        <td><%= circuito.cidade %></td>
                        <td><%= circuito.estado %></td>
                        <td><%= circuito.ano %></td>
                        <td><%= circuito.contato %></td>
                        <td><%= circuito.telefone_contato %></td>
                        <td align="center"><%= link_to 'Visualizar', circuito %></td>
                        <td align="center"><%= link_to 'Editar', edit_circuito_path(circuito) %></td>
                        <td align="center"><%= link_to 'Excluir', circuito, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class: 'btn btn-danger' %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table> 
          </div>
    </div>  
  </div>    
</div>
<br>

<%= link_to 'Novo Circuito', new_circuito_path, class: 'btn btn-primary' %>

app/views/circuitos/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Novo Circuito</h2>
    </div>
</div>

<%= render 'form' %>
</br>
<%= link_to 'Voltar', circuitos_path, class: 'btn btn-default' %>

app/views/circuitos/show.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Visualizar Circuito</h2>
    </div>
</div>
<% unless notice.nil? %>
<div class="alert alert-success alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
  <p id="notice"><%= notice %></p>
</div>
<%end%>

<p>
  <strong>Nome:</strong>
  <%= @circuito.nome %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @circuito.cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @circuito.estado %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @circuito.ano %>
</p>

<p>
  <strong>Contato:</strong>
  <%= @circuito.contato %>
</p>

<p>
  <strong>Telefone contato:</strong>
  <%= @circuito.telefone_contato %>
</p>

<p>
  <strong>Telefone contato 2:</strong>
  <%= @circuito.telefone_contato_2 %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @circuito.descricao %>
</p>

<%= link_to 'Editar', edit_circuito_path(@circuito), class: 'btn btn-default' %> |
<%= link_to 'Voltar', circuitos_path, class: 'btn btn-default' %>