config/routes.rb
Rails.application.routes.draw do
  
  resources :evento_vaquejadas
  resources :circuitos
  resources :operadors
  resources :funcaos
  devise_for :users
  
  get 'home/index'

  root 'home#index'

  

  resources :vaqueiros do
    collection do
      get 'teste'
    end
  end

  get 'home/inicial'
    

end

app/models/funcao.rb
class Funcao < ActiveRecord::Base
	validates_presence_of :tipo

	has_many :operador, :dependent => :restrict_with_error 
end

app/controllers/funcaos_controller.rb
class FuncaosController < ApplicationController
  before_action :set_funcao, only: [:show, :edit, :update, :destroy]
  
  # GET /funcaos
  # GET /funcaos.json
  def index
    @funcaos = Funcao.all
  end

  # GET /funcaos/1
  # GET /funcaos/1.json
  def show
  end

  # GET /funcaos/new
  def new
    @funcao = Funcao.new
  end

  # GET /funcaos/1/edit
  def edit
  end

  # POST /funcaos
  # POST /funcaos.json
  def create
    @funcao = Funcao.new(funcao_params)

    respond_to do |format|
      if @funcao.save
        format.html { redirect_to @funcao, notice: 'Função foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @funcao }
      else
        format.html { render :new }
        format.json { render json: @funcao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcaos/1
  # PATCH/PUT /funcaos/1.json
  def update
    respond_to do |format|
      if @funcao.update(funcao_params)
        format.html { redirect_to @funcao, notice: 'Função foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @funcao }
      else
        format.html { render :edit }
        format.json { render json: @funcao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcaos/1
  # DELETE /funcaos/1.json
  def destroy
    respond_to do |format|
    if @funcao.destroy
        format.html { redirect_to funcaos_url, notice: 'Função foi excluída com sucesso.' }
    else
        format.html { redirect_to funcaos_url, alert: @funcao.errors.messages[:base]}
    end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcao
      @funcao = Funcao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcao_params
      params.require(:funcao).permit(:descricao, :tipo)
    end
end

app/helpers/funcaos_helper.rb
module FuncaosHelper
end

app/views/funcaos/_form.html.erb
<%= form_for(@funcao) do |f| %>
<% if @funcao.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
      <h4><%= pluralize(@funcao.errors.count, "erro(s)") %> Não foi possível salvar Função:</h4>
      <ul>
          <% @funcao.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-8">
      <%= f.label :tipo, class: 'control-label' %><br>
      <%= f.text_field :tipo, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-8">
      <%= f.label :descricao, class: 'control-label' %><br>
      <%= f.text_area :descricao, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/funcaos/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Editar Função</h2>
    </div>
    <!-- /.col-lg-12 -->
</div>

<%= render 'form' %>
</br>
<%= link_to 'Visualizar', @funcao, class: 'btn btn-default' %> |
<%= link_to 'Voltar', funcaos_path, class: 'btn btn-default' %>

app/views/funcaos/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Lista de Funções</h2>
    </div>
    <!-- /.col-lg-12 -->
</div>
<% if notice or alert %>
<div class="alert alert-<%= alert ? 'warning' : 'success' %> alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
  <p id="notice"><%= notice %></p><p id="alert"><%= alert %></p>
</div>
<%end%>

<div class="col-md-12">
  <div class="panel panel-default">
      <div class="panel-heading">
          Funções
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
          <div class="table-responsive">
              <table class="table table-striped table-bordered table-hover">
                  <thead>
                    <tr>
                      <th>Tipo</th>
                      <th>Descrição</th>
                      <th colspan="3">Ações</th>
                    </tr>
                  </thead>
                  
                  <tbody>
                    <% @funcaos.each do |funcao| %>
                      <tr>
                        <td><%= funcao.tipo %></td>
                        <td><%= funcao.descricao %></td>
                        <td align="center"><%= link_to 'Visualizar', funcao %></td>
                        <td align="center"><%= link_to 'Editar', edit_funcao_path(funcao) %></td>
                        <td align="center"><%= link_to 'Excluir', funcao, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class: 'btn btn-danger' %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table> 
          </div>
    </div>  
  </div>    
</div>

</br>

<%= link_to 'Nova Função', new_funcao_path, class: 'btn btn-primary' %>

app/views/funcaos/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Nova Função</h2>
    </div>
</div>

<%= render 'form' %>
</br>
<%= link_to 'Voltar', funcaos_path, class: 'btn btn-default' %>

app/views/funcaos/show.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Visualizar Função</h2>
    </div>
</div>
<% unless notice.nil? %>
<div class="alert alert-success alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
  <p id="notice"><%= notice %></p>
</div>
<%end%>

<p>
  <strong>Tipo:</strong>
  <%= @funcao.tipo %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @funcao.descricao %>
</p>


<%= link_to 'Editar', edit_funcao_path(@funcao), class: 'btn btn-default' %> |
<%= link_to 'Voltar', funcaos_path, class: 'btn btn-default' %>